version: "3"
services:
        node-app:
            container_name: node-cont
            image: login-app:new
            restart: always
            build: .
            ports:
              - "51005:51005"
            links:
              - mongo
        mongo:
              container_name: mongo_new
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27018:27017'
        mysql-service:
                container_name: node-mysql
                image: mysql:5.7
                volumes:
                  - ./dbdata:/var/lib/mysql
                ports:
                  - '3301:3306'
                restart: always
                environment:
                  - MYSQL_ROOT_HOST=root
                  - MYSQL_ROOT_PASSWORD=root
                  - MYSQL_DATABASE=nodeapp
